[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "cashdive"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "psycopg2-binary",
    "requests",
    "prettytable",
    "pyfiglet",
    "itsdangerous"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
]

[tool.setuptools]
py-modules = [
    "api",
    "auth",
    "database",
    "models",
    "repositories",
]